version: '3.6'
volumes:
  dbdata:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_data_base
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nasa_space_exploration_database
      - MYSQL_ROOT_USER=root
    ports:
      - "33061:3306"
